model_path: "model/plant_disease_model.h5"

class_names:
  - Pepper__bell__Bacterial_spot
  - Pepper__bell__healthy
  - Potato__Early_blight
  - Potato__healthy
  - Potato__Late_blight
  - Tomato__Target_Spot
  - Tomato__Tomato_mosaic_virus
  - Tomato__Tomato_YellowLeaf_Curl_Virus
  - Tomato__Bacterial_spot
  - Tomato__Early_blight
  - Tomato__healthy
  - Tomato__Late_blight
  - Tomato__Leaf_Mold
  - Tomato__Septoria_leaf_spot
  - Tomato__Spider_mites_Two_spotted_spider_mite
